### PR TITLE
Feature/i70/create model schemas

### PR DESCRIPTION
**Pull request by Rustyiller**
syntax to edit, u can edit multiple values at the same time
[
	{
		"stat": "strength", "value": 99
	}
]

### CODE REVIEW

**Review by sj-lt — APPROVED** [review]
looks ok. one thing that you dont need to parse json manually and second would be nice if u clean routes and views but approved anyway

**Review by kulaszewicz — CHANGES_REQUESTED** [review]
Add some validation, add required prop for model schemas, change stats names to the one's that Pawel suggested

**Review by kulaszewicz — APPROVED** [review]
Good

**Review by BennyKayer — APPROVED** [review]
Good

**Pull request merged**
